django_blog/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
  path('', views.index, name='index'),
  path('sign-in', views.sign_in, name='sign_in'),
  path('sign-up', views.sign_up, name='sign_up'),
  path('register-success', views.register_success, name='register_success'),
  path('sign-in-success', views.sign_in_success, name='sign_in_success')
]

django_blog/django_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

django_blog/blog/models.py
from django.db import models

class User(models.Model):
  username = models.CharField(max_length=50, primary_key=True)
  password = models.CharField(max_length=50)

  def __str__(self):
    return self.username

django_blog/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import loader
from blog.models import User
import hashlib

def index(request):
  return render(request, 'blog/index.html')


def register_success(request):
  username = request.POST['username']
  password = request.POST['password']
  hashed_pass = hashlib.sha512(password.encode('utf-8')).hexdigest()

  try:
    User.objects.get(username=username)
    return HttpResponse("<h1>Username already exist<h1>")
  except User.DoesNotExist:
    new_user = User(password=hashed_pass, username=username)
    new_user.save()
    return HttpResponse("<h1>User registered successfully!<h1>")


def sign_in_success(request):
  username = request.POST['username']
  password = request.POST['password']
  hashed_pass = hashlib.sha512(password.encode('utf-8')).hexdigest()

  try:
    user = User.objects.get(username=username, password=hashed_pass)
    return HttpResponse("<h1>Welcome "+ user.username +", sign-in success!<h1>")
  except User.DoesNotExist:
    return HttpResponse("<h1>Wrong username or password<h1>")


def sign_in(request):
  return render(request, 'blog/sign_in.html')


def sign_up(request):
  return render(request, 'blog/sign_up.html')

django_blog/blog/templates/blog/index.html
<h1>Homepage</h1>
<a href="{% url 'blog:sign_in' %}">Sign-In</a><br>
<a href="{% url 'blog:sign_up' %}">Sign-Up</a>

django_blog/blog/templates/blog/sign_in.html
<h1>Sign-in</h1>
<form action="{% url 'blog:sign_in_success' %}" method="post">
  {% csrf_token %}
  Username: 
  <input type="text" name="username" id="username">

  Password:
  <input type="password" name="password" id="password">

  <input type="submit" value="Sign-Up">
</form>

django_blog/blog/templates/blog/sign_up.html
<h1>Sign-up</h1>
<form action="{% url 'blog:register_success' %}" method="post">
  {% csrf_token %}
  Username: 
  <input type="text" name="username" id="username">

  Password:
  <input type="password" name="password" id="password">

  <input type="submit" value="Sign-Up">
</form>